services:
  composer:
    image: prooph/composer:8.2
    container_name: composer
    volumes:
      - .:/app
    command: install

  php:
    image: prooph/php:8.2-cli
    container_name: php
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
    volumes:
      - .:/app
    network_mode: "host"
    command: vendor/bin/phpunit
    depends_on:
      - firefox

  firefox:
    image: selenium/standalone-firefox:4.24.0-20240907
    shm_size: "2gb"
    container_name: firefox
    ports:
      - "4444:4444"
      - "7900:7900"
